Repository openshift-service-mesh/federation, pull requests merged in 2024-10, with the labels that each got.

#47 Update go module name and imports
  .github/workflows/build.yaml
  README.md
  chart/values.yaml
  cmd/federation-controller/main.go
  go.mod
  internal/pkg/common/match_exported.go
  internal/pkg/fds/exported_service_generator.go
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/fds/import_handler.go
  internal/pkg/fds/imported_service_store.go
  internal/pkg/informer/service_export_event_handler.go
  internal/pkg/informer/service_export_event_handler_test.go
  internal/pkg/istio/config_factory.go
  internal/pkg/mcp/destination_rule_generator.go
  internal/pkg/mcp/gateway_generator.go
  internal/pkg/mcp/gateway_generator_test.go
  internal/pkg/mcp/service_entry_generator.go
  internal/pkg/mcp/service_entry_generator_test.go
  internal/pkg/mcp/virtual_service_generator.go
  internal/pkg/mcp/workload_entry_generator.go
  internal/pkg/mcp/workload_entry_generator_test.go
  internal/pkg/xds/adss/adss_handler.go
  internal/pkg/xds/adss/grpc_server.go
Labels: size/L, okay to merge

#48 Add make target for fixing imports
  Makefile
  cmd/federation-controller/main.go
  internal/api/federation/v1alpha1/exported_service.pb.go
  internal/pkg/common/match_exported.go
  internal/pkg/fds/exported_service_generator.go
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/fds/import_handler.go
  internal/pkg/informer/service_export_event_handler.go
  internal/pkg/informer/service_export_event_handler_test.go
  internal/pkg/mcp/destination_rule_generator.go
  internal/pkg/mcp/gateway_generator.go
  internal/pkg/mcp/gateway_generator_test.go
  internal/pkg/mcp/service_entry_generator.go
  internal/pkg/mcp/service_entry_generator_test.go
  internal/pkg/mcp/virtual_service_generator.go
  internal/pkg/mcp/workload_entry_generator.go
  internal/pkg/mcp/workload_entry_generator_test.go
  internal/pkg/xds/adss/adss_handler.go
  internal/pkg/xds/adss/grpc_server.go
Labels: size/L, okay to merge

#54 Introduce k8s config mode
  chart/templates/clusterrole.yaml
  chart/templates/deployment.yaml
  cmd/federation-controller/main.go
  internal/pkg/config/federation_config.go
  internal/pkg/istio/config_factory.go
  internal/pkg/kube/destination_rule_reconciler.go
  internal/pkg/kube/gateway_reconciler.go
  internal/pkg/kube/reconciler.go
  internal/pkg/kube/reconciler_manager.go
  internal/pkg/kube/service_entry_reconciler.go
  internal/pkg/kube/virtual_service_reconciler.go
  internal/pkg/kube/workload_entry_reconciler.go
  internal/pkg/mcp/service_entry_generator_test.go
  internal/pkg/mcp/workload_entry_generator_test.go
Labels: okay to merge, size/XL

#57 Update chart and examples
  chart/templates/deployment.yaml
  chart/values.yaml
  examples/README.md
  examples/ip-address-pool.tmpl.yaml
  examples/k8s/east-mesh.yaml
  examples/k8s/west-mesh.yaml
  examples/mcp/east-mesh.yaml
  examples/mcp/west-mesh.yaml
Labels: size/L, okay to merge

#58 ci: restore job for unit tests
  .github/workflows/build.yaml
Labels: okay to merge, size/S

#60 test: fix flaky test case that checks if a hostname is unreachable
  test/e2e/traffic_test.go
Labels: okay to merge, size/XS
