Repository openshift-service-mesh/federation, pull requests merged in 2024-11, with the labels that each got.

#61 test: increase coverage and improve performance
  Makefile
  README.md
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/mcp/gateway_generator_test.go
  internal/pkg/mcp/service_entry_generator_test.go
  internal/pkg/mcp/workload_entry_generator_test.go
  test/e2e/common/setup.go
  test/e2e/common/traffic_tests.go
  test/e2e/k8s/main_test.go
  test/e2e/main_test.go
  test/e2e/mcp/main_test.go
  test/e2e/traffic_test.go
  test/scripts/generate_istio_manifests.sh
  test/scripts/kind_provisioner.sh
  test/scripts/lib.sh
  test/testdata/istio/k8s/east.yaml
  test/testdata/istio/k8s/west.yaml
  test/testdata/istio/mcp/east.yaml
  test/testdata/istio/mcp/west.yaml
  test/testdata/manifests/1.22.1/istio.yaml
  test/testdata/manifests/1.23.0/istio.yaml
Labels: okay to merge, size/XXL

#65 feat(build): configurable container builder
  Makefile
Labels: okay to merge, size/XS

#67 chore(errors): wraps errors using %w
  internal/pkg/fds/exported_service_generator.go
  internal/pkg/fds/import_handler.go
  internal/pkg/istio/config_factory.go
  internal/pkg/kube/destination_rule_reconciler.go
  internal/pkg/kube/gateway_reconciler.go
  internal/pkg/kube/service_entry_reconciler.go
  internal/pkg/kube/virtual_service_reconciler.go
  internal/pkg/kube/workload_entry_reconciler.go
  internal/pkg/mcp/gateway_generator.go
  internal/pkg/mcp/service_entry_generator.go
  internal/pkg/mcp/workload_entry_generator.go
  internal/pkg/xds/adsc/adsc.go
  test/e2e/common/setup.go
  test/e2e/common/traffic_tests.go
Labels: okay to merge, size/M

#66 test: upload local version of federation controller to kind clusters
  Makefile
  README.md
  test/scripts/kind_provisioner.sh
  test/scripts/lib.sh
Labels: okay to merge, size/M

#68 fix(make): ensures test image is built for kind setup
  Makefile
Labels: okay to merge, size/XS

#69 feat(make): introduces help target
  Makefile
Labels: okay to merge, size/M

#74 fix(git): ignores demo cert folders
  .gitignore
Labels: okay to merge, size/XS

#72 fds: restart client on connection failure during startup
  cmd/federation-controller/main.go
  internal/pkg/xds/adsc/adsc.go
Labels: okay to merge, size/M

#73 feat(k8s): run all reconcilers in a single pass
  internal/pkg/kube/reconciler_manager.go
Labels: okay to merge, size/S

#75 Drop support for MCP mode
  Makefile
  README.md
  chart/Chart.yaml
  chart/templates/deployment.yaml
  chart/templates/service.yaml
  chart/values.yaml
  cmd/federation-controller/main.go
  examples/README.md
  examples/east-mesh.yaml
  examples/mcp/east-mesh.yaml
  examples/mcp/west-mesh.yaml
  examples/spire/federation-controller.yaml
  examples/west-mesh.yaml
  internal/pkg/config/federation_config.go
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/mcp/destination_rule_generator.go
  internal/pkg/mcp/gateway_generator.go
  internal/pkg/mcp/gateway_generator_test.go
  internal/pkg/mcp/serialize.go
  internal/pkg/mcp/service_entry_generator.go
  internal/pkg/mcp/service_entry_generator_test.go
  internal/pkg/mcp/virtual_service_generator.go
  internal/pkg/mcp/workload_entry_generator.go
  internal/pkg/mcp/workload_entry_generator_test.go
  internal/pkg/xds/adss/adss_handler.go
  internal/pkg/xds/adss/grpc_server.go
  test/e2e/common/setup.go
  test/e2e/k8s/main_test.go
  test/e2e/mcp/main_test.go
  test/e2e/spire/main_test.go
  test/testdata/istio/mcp/east.yaml
  test/testdata/istio/mcp/west.yaml
Labels: okay to merge, size/XXL

#77 helm: set default value for `federation.meshPeers.local.controlPlane.namespace`
  chart/values.yaml
  examples/federation-controller.yaml
  test/testdata/federation-controller.yaml
Labels: okay to merge, size/S

#78 docs: fixes typo in example verification
  examples/README.md
Labels: okay to merge, size/XS

#76 helm: hardcode service name
  chart/templates/deployment.yaml
  chart/templates/service.yaml
  internal/pkg/istio/config_factory.go
Labels: okay to merge, size/XS

#79 feat(make): customizable build target
  Makefile
Labels: okay to merge, size/XS

#81 fds: fix reconnect delay
  cmd/federation-controller/main.go
Labels: okay to merge, size/XS

#82 fix(make): configurable binary output directory
  Makefile
Labels: okay to merge, size/S

#83 chore(make): removes excessive // in paths
  Makefile
Labels: okay to merge, size/XS

#85 chore: changes yaml to json tags
  internal/pkg/config/federation_config.go
Labels: okay to merge, size/M

#90 feat(ci): ensures license headers are added
  .github/workflows/linters.yaml
Labels: okay to merge, size/S

#86 chore(cli): removes Cobra cli library
  cmd/federation-controller/main.go
  go.mod
Labels: okay to merge, size/M

#92 feat(build): simplifies local image upload strategy
  Makefile
  test/scripts/cluster.sh
  test/scripts/kind_provisioner.sh
  test/scripts/lib.sh
Labels: size/L, okay to merge
