Repository openshift-service-mesh/federation, pull requests merged in 2024-12, with the labels that each got.

#94 chore(kind): simplifies cluster setup
  test/scripts/cluster.sh
  test/scripts/kind_provisioner.sh
  test/scripts/lib.sh
Labels: okay to merge, size/M

#97 fix(ci): uses python3 instead of unzip
  Makefile
Labels: okay to merge, size/XS

#96 fix(make): ensures tools installation for e2e tests
  Makefile
Labels: okay to merge, size/XS

#95 fix(make): ensures binary is built against up-to-date code
  Makefile
Labels: okay to merge, size/XS

#98 chore(config): Move parseConfiguration to the config package
  cmd/federation-controller/main.go
  internal/pkg/config/parse.go
Labels: okay to merge, size/M

#102 feat(config): controller's namespace autodiscovery
  chart/templates/deployment.yaml
  cmd/federation-controller/main.go
  internal/pkg/config/cluster.go
Labels: okay to merge, size/M

#100 feat(fds): groups federated services by remote peers
  api/proto/federation/v1alpha1/exported_service.proto
  cmd/federation-controller/main.go
  internal/api/federation/v1alpha1/exported_service.pb.go
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/fds/import_handler.go
  internal/pkg/fds/imported_service_store.go
  internal/pkg/istio/config_factory.go
  internal/pkg/xds/adsc/adsc.go
  internal/pkg/xds/adsc/response_handler.go
  internal/pkg/xds/adss/adss_handler.go
Labels: size/L, okay to merge

#105 fix(e2e): aligns echo app version with Istio
  test/e2e/common/setup.go
Labels: okay to merge, size/XS

#103 feat(build): adds fix-imports to build target
  Makefile
Labels: okay to merge, size/XS

#104 fix(cmd): wait for root context to finish
  cmd/federation-controller/main.go
Labels: okay to merge, size/XS

#107 fix(config): fails on unknown fields
  internal/pkg/config/parse.go
Labels: okay to merge, size/XS

#108 fix(e2e): creates more subnets for kind clusters
  test/scripts/find_subnets.py
Labels: okay to merge, size/XS

#109 fix(make): includes kind as a local binary
  Makefile
Labels: okay to merge, size/M

#111 fix(deps): pins protobuf versions
  Makefile
  internal/api/federation/v1alpha1/exported_service.pb.go
Labels: okay to merge, size/M

#113 fix(make): prevents redundant binary downloads
  Makefile
Labels: okay to merge, size/S

#114 chore(make): simplifies build target
  Makefile
Labels: okay to merge, size/XS

#112 chore(istio): add unit tests for ServiceEntries
  internal/pkg/istio/config_factory_test.go
  internal/pkg/istio/testdata/envoy-filters/fds.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-b-ns-1-port-443.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-b-ns-1-port-80.yaml
  internal/pkg/istio/testdata/service-entries/dns/fds.yaml
  internal/pkg/istio/testdata/service-entries/dns/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/dns/svc-b-ns-1.yaml
  internal/pkg/istio/testdata/service-entries/ip/fds.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-b-ns-1.yaml
Labels: size/L, okay to merge

#115 feat(make): replaces `go get` with `deps` target
  Makefile
Labels: okay to merge, size/S

#116 feat(make): generates code only on API changes
  Makefile
Labels: okay to merge, size/S

#118 feat(adsc): adds peer name to the logger
  internal/pkg/xds/adsc/adsc.go
Labels: okay to merge, size/S

#117 fix(make): runs all e2e suites
  Makefile
Labels: okay to merge, size/XS
