Repository openshift-service-mesh/federation, pull requests merged in 2025-01, with the labels that each got.

#122 Change project domain to openshift-service-mesh.io
  examples/README.md
  internal/pkg/istio/config_factory.go
  internal/pkg/istio/config_factory_test.go
  internal/pkg/istio/testdata/envoy-filters/fds.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-b-ns-1-port-443.yaml
  internal/pkg/istio/testdata/envoy-filters/svc-b-ns-1-port-80.yaml
  internal/pkg/istio/testdata/service-entries/dns/fds.yaml
  internal/pkg/istio/testdata/service-entries/dns/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/dns/svc-b-ns-1.yaml
  internal/pkg/istio/testdata/service-entries/ip/fds.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-b-ns-1.yaml
  internal/pkg/kube/destination_rule_reconciler.go
  internal/pkg/kube/envoy_filter_reconciler.go
  internal/pkg/kube/peer_authentication_reconciler.go
  internal/pkg/kube/service_entry_reconciler.go
  internal/pkg/kube/workload_entry_reconciler.go
  internal/pkg/openshift/config_factory.go
  internal/pkg/xds/types.go
Labels: okay to merge, size/M

#129 fix(examples): adjust helm values to recent API changes
  examples/README.md
  examples/kind/east-federation-controller.yaml
  examples/kind/west-federation-controller.yaml
  examples/openshift/east-federation-controller.yaml
  examples/openshift/west-federation-controller.yaml
  examples/spire/README.md
Labels: okay to merge, size/S

#126 chore(make): removes reference to non existing target
  Makefile
Labels: okay to merge, size/XS

#127 chore(make): ensures protoc generated code is correctly formatted
  Makefile
Labels: okay to merge, size/XS

#128 feat(kube): set up controller and reconciler template for MeshFederation
  chart/templates/clusterrole.yaml
  cmd/federation-controller/main.go
  go.mod
  go.sum
  internal/controller/meshfederation_controller.go
Labels: size/L, okay to merge

#132 chore(fds-server): simplifies server run logic
  internal/pkg/xds/adss/grpc_server.go
Labels: okay to merge, size/S

#133 feat(fds-client): enables sending discovery requests
  internal/pkg/xds/adsc/adsc.go
Labels: okay to merge, size/XS

#131 feat(api): rename ExportedService to FederatedService and replace name and namespace with hostname
  api/proto/federation/v1alpha1/exported_service.proto
  api/proto/federation/v1alpha1/federated_service.proto
  internal/api/federation/v1alpha1/exported_service.pb.go
  internal/api/federation/v1alpha1/federated_service.pb.go
  internal/api/federation/v1alpha1/federated_service_deepcopy.gen.go
  internal/pkg/fds/exported_service_generator.go
  internal/pkg/fds/exported_service_generator_test.go
  internal/pkg/fds/import_handler.go
  internal/pkg/fds/imported_service_store.go
  internal/pkg/istio/config_factory.go
  internal/pkg/istio/config_factory_test.go
  internal/pkg/istio/testdata/service-entries/dns/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/dns/svc-b-ns-1.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-a-ns-2.yaml
  internal/pkg/istio/testdata/service-entries/ip/svc-b-ns-1.yaml
Labels: okay to merge, size/XL

#134 fix(fds): simplifies sync logic
  cmd/federation-controller/main.go
  internal/pkg/xds/adsc/adsc.go
  internal/pkg/xds/adss/adss_handler.go
  internal/pkg/xds/adss/grpc_server.go
Labels: okay to merge, size/M

#136 feat(api): add crd and reconciler templates for FederatedService
  PROJECT
  api/v1alpha1/federatedservice_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/crds/federation.openshift-service-mesh.io_federatedservices.yaml
  chart/templates/clusterrole.yaml
  cmd/federation-controller/main.go
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/rbac/federatedservice_editor_role.yaml
  config/rbac/federatedservice_viewer_role.yaml
  config/samples/federation_v1alpha1_federatedservice.yaml
  config/samples/kustomization.yaml
  internal/controller/federatedservice_controller.go
Labels: size/L, okay to merge

#135 chore(fds): renames peer to remote
  cmd/federation-controller/main.go
  internal/pkg/xds/adsc/adsc.go
Labels: okay to merge, size/XS

#154 chore: renames err vars to follow conventions
  cmd/federation-controller/main.go
  internal/pkg/xds/adsc/adsc.go
Labels: okay to merge, size/S

#155 feat(cmd): hides ctrl-runtime implementation behind the flag
  cmd/federation-controller/main.go
Labels: okay to merge, size/M

#160 feat(build): replaces goimports with gci
  Makefile
  cmd/federation-controller/main.go
  internal/controller/meshfederation_controller.go
  internal/pkg/config/parse.go
  internal/pkg/fds/imported_service_store.go
  test/e2e/scenarios/remote_dns_name/main_test.go
  test/e2e/scenarios/remote_ip/main_test.go
  test/e2e/scenarios/spire/main_test.go
  test/e2e/scenarios/spire/setup.go
  test/e2e/setup/cluster_cmds.go
  test/e2e/setup/coredns/patch.go
  test/e2e/setup/federation.go
  test/e2e/traffic_tests.go
Labels: okay to merge, size/M

#163 feat(ctlr): introduces constructor function
  cmd/federation-controller/main.go
  internal/controller/federatedservice/federatedservice_controller.go
  internal/controller/meshfederation/meshfederation_controller.go
Labels: okay to merge, size/M

#162 chore(build): reorganizes Makefile
  Makefile
  Makefile.tooling.mk
Labels: size/L, okay to merge

#161 fix(api): changes scope of CRs to Namespaced
  PROJECT
  api/v1alpha1/federatedservice_types.go
  api/v1alpha1/meshfederation_types.go
  chart/crds/federation.openshift-service-mesh.io_meshfederations.yaml
Labels: okay to merge, size/XS

#159 chore(structure): moves current federation setup logic to legacy pkg
  cmd/federation-controller/main.go
  internal/pkg/istio/config_factory.go
  internal/pkg/istio/config_factory_test.go
  internal/pkg/legacy/fds/exported_service_generator.go
  internal/pkg/legacy/fds/exported_service_generator_test.go
  internal/pkg/legacy/fds/import_handler.go
  internal/pkg/legacy/fds/imported_service_store.go
  internal/pkg/legacy/informer/resource_controller.go
  internal/pkg/legacy/informer/service_export_event_handler.go
  internal/pkg/legacy/informer/service_export_event_handler_test.go
  internal/pkg/legacy/kube/destination_rule_reconciler.go
  internal/pkg/legacy/kube/envoy_filter_reconciler.go
  internal/pkg/legacy/kube/gateway_reconciler.go
  internal/pkg/legacy/kube/peer_authentication_reconciler.go
  internal/pkg/legacy/kube/reconciler.go
  internal/pkg/legacy/kube/reconciler_manager.go
  internal/pkg/legacy/kube/route_reconciler.go
  internal/pkg/legacy/kube/service_entry_reconciler.go
  internal/pkg/legacy/kube/workload_entry_reconciler.go
  internal/pkg/legacy/xds/adsc/adsc.go
  internal/pkg/legacy/xds/adsc/response_handler.go
  internal/pkg/legacy/xds/adss/adss_handler.go
  internal/pkg/legacy/xds/adss/grpc_server.go
  internal/pkg/legacy/xds/adss/request_handler.go
  internal/pkg/legacy/xds/push_request.go
  internal/pkg/legacy/xds/types.go
Labels: okay to merge, size/M

#164 feat(ctrl): encapsulates finalizer logic in reusable pkg
  internal/controller/finalizer/types.go
  internal/controller/retry.go
Labels: size/L, okay to merge

#166 feat(api): introduces MeshFederation API
  Makefile.tooling.mk
  api/v1alpha1/meshfederation_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/crds/federation.openshift-service-mesh.io_meshfederations.yaml
Labels: size/L, okay to merge

#171 docs: initial architectural diagram
  docs/arch/diagrams/README.md
  docs/arch/diagrams/export.sh
  docs/arch/diagrams/federation-controllers-overview.png
  docs/arch/diagrams/federation-controllers-relationships.png
  docs/arch/diagrams/federation-controllers.drawio
Labels: okay to merge, size/XL

#165 feat(ctrl): predicate on finalizer change
  internal/controller/meshfederation/meshfederation_controller.go
  internal/controller/predicate.go
Labels: okay to merge, size/M

#167 feat(testing): introduces k8s envtest skeleton
  .gitignore
  Makefile
  Makefile.func.mk
  Makefile.tooling.mk
  api/v1alpha1/meshfederation_types.go
  cmd/federation-controller/main.go
  go.mod
  go.sum
  internal/api/federation/v1alpha1/federated_service.pb.go
  internal/controller/meshfederation/meshfederation_controller.go
  internal/controller/meshfederation/meshfederation_controller_test.go
  internal/controller/meshfederation/suite_test.go
  internal/controller/scheme.go
  internal/controller/types.go
  test/k8senvtest/bootstrap.go
  test/k8senvtest/cleaner.go
  test/k8senvtest/config.go
  test/testdata/crds/external/istio.yaml
  test/testdata/crds/external/route.openshift.io_routes.yaml
Labels: okay to merge, size/XXL

#174 docs: updates diagrams to reflect new names
  .gitignore
  docs/arch/diagrams/federation-controllers-overview.png
  docs/arch/diagrams/federation-controllers-relationships.png
  docs/arch/diagrams/federation-controllers.drawio
Labels: okay to merge, size/M

#106 docs: improve README
  DEVELOPER.md
  README.md
  docs/arch/diagrams/overview.svg
Labels: size/L, okay to merge

#176 docs: updates dev guide
  DEVELOPER.md
  Makefile
Labels: okay to merge, size/M

#177 docs: add Kiali and OpenShift Monitoring to the example deployment
  examples/README.md
  examples/openshift/enable-user-workload-monitoring.yaml
  examples/openshift/kiali-rbac.yaml
  examples/openshift/kiali.yaml
  examples/openshift/pod-monitor.yaml
  examples/openshift/service-monitor.yaml
Labels: size/L, okay to merge
